image: node:latest

stages:
  - install
  - build
  - deploy_prod

cache:
  paths:
    - node_modules/
    - dist/

install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 week

compile_typescript:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

test_environment:
  stage: deploy_prod
  image: ruby:latest
  only:
    - master
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=api-dados-binno --api-key=$HEROKU_API_KEY
