image: node:latest

stages:
  - install
  - build
  - db_migrate
  - deploy_prod

cache:
  paths:
    - node_modules/
    - dist/

install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

compile_typescript:
  stage: build
  only:
    - master
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

configure_databse:
  stage: db_migrate
  only:
    - master
  script:
    - export HOST_DB=$HOST_DB
    - export USERNAME_DB=$USERNAME_DB
    - export PASSWD_DB=$PASSWD_DB
    - export DB_NAME=$DB_NAME
    - export SSL_CONNECTION=true
    - export NODE_ENV=prod
    - npm run migrate

test_environment:
  stage: deploy_prod
  image: ruby:latest
  when: manual
  only:
    - master
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=api-dados-binno --api-key=$HEROKU_API_KEY
